---
title: "Final_Lab_SG"
author: "Sarah Grant"
format: 
  html:
    message: false
    echo: false
---

```{r}
#| message: false
#| warning: false
here::i_am("science_fiction.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(knitr)
library(ggplot2)
```

```{r}
#| message: false
#| warning: false
planets <- vroom(here("data/data_planets.csv"))
stardata <- vroom(here("data/star_data.csv"))
startype <- vroom(here("data/star_types.csv"))
yerkes <- vroom(here("data/Yerkes_luminosity_classes.csv"))
```

## Question 1

Commit of main dataset complete

## Question 2 - Link to Github Repository

Please find the github project via this [link](https://github.com/sarahgrant1/science_fiction).

## Question 3 - Verifying the Validity of the Loading Process

```{r}
expected_planets = 1085
expected_variables = 8
```

```{r}
if (nrow(planets) == expected_planets && ncol(planets) == expected_variables) {
  cat("Loading process has been successful. Number of planets and variables indeed match the expected values.\n")
} else {
  stop("Uh oh! Loading process has not been successful.\n")
}
```
```{r}
planet <- na.omit(planets)
numerical_variables <- c("Mass (Earth)", "Relative Radius", "density (earth)")
non_numerical_variables <- sapply(planets[, numerical_variables], function(x) any(!is.na(as.numeric(x)) & !is.finite(as.numeric(x))))

if (any(non_numerical_variables)) {
  stop("Uh oh! Some of the values within these variables are not recognised as numerical.\n")
} else {
  cat("All numerical values are recognised as numerical.")
}
```

## Question 4

```{r}
num_observations <- nrow(planets)
num_variables <- ncol(planets)

missing_values_per_var <- colSums(is.na(planets))

missing_obvs <- sum(apply(planets, 1, anyNA))

table_qu4 <- data.frame(
  Metric = c("Number of Observations", "Number of Variables", "Missing Values per Variable", "Observations with at Least One Missing Value"),
  Value = c(num_observations, num_variables, toString(missing_values_per_var), missing_obvs)
)

knitr::kable(table_qu4, format = "markdown")
```

